stages:
  - build

intheo-latest:
  stage: build
  image: rust:latest
  script:
    - cd intheo/
    - cargo build --verbose

intheo-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cd intheo/
    - cargo build --verbose
  allow_failure: true
