image: node:alpine

build-job:
  stage: build
  script:
    - ':'

test-job:
  stage: test
  script:
    - ':'

pages:
  stage: deploy
  before_script:
    - apk update
    - apk --update add texlive
    - PATH=/usr/local/texlive/bin/x86_64-linuxmusl:$PATH
    - tlmgr install collection-latexextra collection-luatex collection-langjapanese
  script:
    - mkdir public/
    - cd type-theory/
    - lualatex main
    - lualatex main
    - cd ../
    - cp type-theory/main.pdf public/type-theory.pdf
  artifacts:
    paths:
      - public/
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
